### ISSUE TITLE
cannot grant accesos to the Google account to a third psrgy app.

### ISSUE THREAD

**Issue by LNDF** [microg/GmsCore#1621]
**Describe the bug**
On the microg implementation of the account picker, it doesnt give thr option to grant access to a third party app to the google account. For example, if i want to make a backup on drive of muy whatsapp messages but i have not granted whatsapp the permission to acces drive, whatsapp gives an error and keeps asking for drive permission but i cannot grant them since microg dosent give me the option.

**To Reproduce**
1. Open an app which requires access to google account (e.g. whatsapp)
2. Go to the page where it asks for permission (e.g. backup page in whatsapp)
3. Do the action that asks the permission (e.g. make a backup on whatsapp)

**Expected behavior**
A popup asking for google account access permission (e.g. drive access permission on whatsapp)

**Screenshots**
![Screenshot_20211215-143030_WhatsApp](https://user-images.githubusercontent.com/24205737/146195492-f696f14e-f7d2-4807-bc61-296b2809acf5.png)

**System**
Android Version: 11
Custom ROM: LineageOS 18.1

**Additional context**
To correctly reproduce this bug, is importsbt to use an account witch doesnt have the access permission grsnted previusly on a gapps-enabled device.

**Comment by LNDF** [comment]
I found out that the permission grabting popuo is just an embedded web page. Could microg implement it un a similar way?

**Comment by namhoang1235** [comment]
Metoo. All thing works for me except WhatsApp backup.

**Comment by guglovich** [comment]
Dialer is not syncing into my Google account.

**Comment by LNDF** [comment]
> Dialer is not syncing into my Google account.

Off topic, that is a different thing. Install the google contact sync qdapter. There is a magisk module forma that.

**Comment by ale5000-git** [comment]
@LNDF
Everything should already be fixed on the latest version.
Could you please try?

**Comment by LNDF** [comment]
Km currently con LOS + microG (version 0.2.22.212658) the issuse is not fixed on that version.

**Comment by ale5000-git** [comment]
The latest version is **_0.2.23.214816_**

**Comment by LNDF** [comment]
Still not working con  0.2.23.214816.
I tap the ask for permission Butrón bit there is no prompt to grantaccess.
