### ISSUE TITLE
[com.car2go] bug / not working. 'play services need to be updated'

### ISSUE THREAD

**Issue by eplinux** [microg/GmsCore#1767]
Affected app
Name: Share Now
Package id: com.car2go

Describe the bug

When opening the app, the map remains blank and the following error message is thrown: 'To use share now, google play services are needed that aren't supported on your device'. Logcat shows:

08-23 12:30:27.861 W/GooglePlayServicesUtil(27862): com.car2go requires the Google Play Store, but it is missing.

Playstore Version is 20.9.20-all [0] [PR] 320416846

To Reproduce

Open the app.
    
Expected behavior

I expect the map to show.

System
Android Version: 11
Custom ROM: Arrow OS V. 11.0 Vanilla

microG
microG Core version: 0.2.24.214816
microG Self-Check results: All ticked

**Comment by LECAGO** [comment]
I am also getting this issue with com.wave.identity app, which also displays maps.
I am on Android 11, LineageOS 18.1, microG 0.2.24.214816 all ticked in self-check.

**Comment by RobertoWa** [comment]
u installed the app by the patched playstore?

**Comment by ale5000-git** [comment]
Updating to the latest [nightly build](https://microg.org/dl/core-nightly.apk) of microG GmsCore should fix this issue, please report if it isn't like this.

**Comment by LECAGO** [comment]
Issue still persists. I don't know if this will help, but I am also getting a weird error on sg.edu.ntu.apps.ntuomnibus app, which was also present in microG 0.2.24.214816 and also still persists in the new nightly build. I'm quite sure this error is microG specific, as I didn't have it when I had NikGapps.

`Error adding script 'https://www.googletagmanager.com/gtag/js?id=G-VV4EZZ14QN to document 'https://apps.ntu.edu.sg/NTUOmnibus`

The mapping portion in the app works fine, although it's slow, probably due to failing to load the script.

**Comment by mar-v-in** [comment]
@eplinux If you are using a patched play store, check that "Play Store (Phonesky) has correct signature" is checked in microG self-check. I can't reproduce any issue with SHARE NOW app.

**Comment by eplinux** [comment]
@mar-v-in You're right, that's weird. Now it's working, maybe they updated their app?

**Comment by ale5000-git** [comment]
I'm closing it since it is now fixed, if not the case please update to the latest [nightly build](https://microg.org/dl/core-nightly.apk) and then if the issue still apply write it here.
