### ISSUE TITLE
Device Health Services: error work with microG

### ISSUE THREAD

**Issue by Izorkin** [microg/GmsCore#1794]
**Affected app**
Name: Device Health Services
Package id: com.google.android.apps.turbo

**Describe the bug**
After installing microG, the "Device Health Services" service starts asking to update Google Play Services.

**To Reproduce**
1. Install firmware.
2. Install Magisk.
3. Install microG.

**Screenshots**
![Screenshot_20220928-201848](https://user-images.githubusercontent.com/26877687/192858732-0a13a055-1f1d-4bbc-b7b1-b2a20e36627d.png)
![Screenshot_20220928-202005](https://user-images.githubusercontent.com/26877687/192858788-19853bb2-3a7d-42c6-8564-77dfe91dbabf.png)

**System**
Android Version: 12
Custom ROM: crDroid.
**microG**
microG Core version: 0.2.24.214816
microG Self-Check results: All ticked

**Comment by ale5000-git** [comment]
It should already be fixed.
Could you please update to the latest [nightly build](https://microg.org/dl/core-nightly.apk) of microG GmsCore and report back?

**Comment by Izorkin** [comment]
@ale5000-git update microG to version 0.2.24.223.315.-35, problem not resolved.

**Comment by ale5000-git** [comment]
It will likely be fixed by #1795

**Comment by Izorkin** [comment]
When can I check? Can you make a new build?

**Comment by ale5000-git** [comment]
I can't, we should wait mar-v-in

**Comment by mar-v-in** [comment]
Which version of Device Health Services are you using?

The 1.25.0 version available on apkmirror only requires gms version 22.24.10 and the nightly already is at 22.33.15, so bumping to 22.36.16 is unlikely to change something. There are also other things that can trigger this notification, maybe you can provide a logcat?

**Comment by Izorkin** [comment]
@mar-v-in result:
```
213002
```

**Comment by Luciogi** [comment]
I also get this error on Nightly Build of microG

![Screenshot_20221001-174001_Settings_1](https://user-images.githubusercontent.com/84625092/193412002-c0800b7c-cc17-4e2e-86fd-bed186a2d996.png)

**Comment by Izorkin** [comment]
Уes i have the same version, which requires version `213002` Google Play.
Or I incorrectly checked required version.

**Comment by Luciogi** [comment]
I got same output as yours

**Comment by ale5000-git** [comment]
There have been some changes that improve compatibility recently (like [this](https://github.com/microg/GmsCore/commit/f4c9ecf1f6fc86101fdd19dbbaa10fb873efffbb)), could you please update to the latest [nightly build](https://microg.org/dl/core-nightly.apk) of microG GmsCore and report back?

PS: The link is the same, but it isn't the same version of before.

**Comment by Izorkin** [comment]
@ale5000-git this update didn't fix the warning :(

**Comment by ale5000-git** [comment]
Probably the app is looking something else then.
Could anyone please take a logcat with the latest nightly build of microG GmsCore?

**Comment by Izorkin** [comment]
How can I collect the log?

**Comment by ale5000-git** [comment]
There is an explanation here: https://wiki.lineageos.org/how-to/logcat
Ignore the thing about "radio buffer" and then post the logcat in this ticket.

**Comment by Izorkin** [comment]
Collected log - [dhs.log](https://github.com/microg/GmsCore/files/9699250/dhs.log)

**Comment by ale5000-git** [comment]
@mar-v-in

```
10-03 19:21:47.895  4326  4326 D UsageReportingService: onBind: Intent { act=com.google.android.gms.usagereporting.service.START pkg=com.google.android.gms }
10-03 19:21:47.902  4326  4593 D UsageReportingService: bound by: GetServiceRequest{serviceId=USAGE_REPORTING, gmsVersion=213002000, packageName='com.google.android.apps.turbo', extras=Bundle[{}]}
10-03 19:21:47.913  8031  8193 W GoogleApiManager: arn could not execute call because it requires feature (usage_and_diagnostics_listener, 1).
10-03 19:21:47.915  8031  8193 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10208; state: ENABLED
10-03 19:21:47.918  8031  8193 W GoogleApiAvailability: GMS core API Availability. ConnectionResult=2, tag=null
10-03 19:21:47.918  8031  8193 W GoogleApiAvailability: java.lang.IllegalArgumentException
10-03 19:21:47.918  8031  8193 W GoogleApiAvailability: 	at agv.a(PG:2)
10-03 19:21:47.918  8031  8193 W GoogleApiAvailability: 	at akm.g(PG:3)
10-03 19:21:47.918  8031  8193 W GoogleApiAvailability: 	at aki.u(PG:24)
10-03 19:21:47.918  8031  8193 W GoogleApiAvailability: 	at aki.f(PG:3)
10-03 19:21:47.918  8031  8193 W GoogleApiAvailability: 	at akm.handleMessage(PG:104)
10-03 19:21:47.918  8031  8193 W GoogleApiAvailability: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-03 19:21:47.918  8031  8193 W GoogleApiAvailability: 	at android.os.Looper.loopOnce(Looper.java:201)
10-03 19:21:47.918  8031  8193 W GoogleApiAvailability: 	at android.os.Looper.loop(Looper.java:288)
10-03 19:21:47.918  8031  8193 W GoogleApiAvailability: 	at android.os.HandlerThread.run(HandlerThread.java:67)
10-03 19:21:47.920  8031  8298 W Zebedee-inferBucketsJob: Models given by config: 1
```

**Comment by ale5000-git** [comment]
@Izorkin
Does it works with microG GmsCore v0.2.25.223616?

**Comment by Izorkin** [comment]
> @Izorkin
> Does it works with microG GmsCore v0.2.25.223616?

Thanks, notification does not appear anymore.
