### ISSUE TITLE
Impossible to update microg from f-droid anymore

### ISSUE THREAD

**Issue by Kommprog** [microg/GmsCore#1805]
Before there was [some problem](https://github.com/lineageos4microg/docker-lineage-cicd/issues/266) with updating it on LineageOS for microg ROM, but it had simple solution, and now no way you can do — signature incompability is the reason.

**Comment by Relected** [comment]
yeah I have the same issue, even when revoking signature spoofing perms from the app its still the same

**Comment by mar-v-in** [comment]
This should be fixed by now. Make sure to update the repo index.

**Comment by billie80** [comment]
I also had to install the update manually even after the repository update but I was not sure about the exact time.
Today however I heard that it still does not work.
There is only a popup saying "not installed".

**Comment by Relected** [comment]
@billie80 yup, still the same issue for me

**Comment by mar-v-in** [comment]
Should also be fixed now (see upstream issue: https://gitlab.com/fdroid/fdroidclient/-/issues/2426)

**Comment by Joduai** [comment]
Got into same problem on my freshly installed arrowos13. I get 'invalid signature" when I want to install from fdroid. 
Maybe I should grant signature spoofing before trying to install from fdroid?
But have no idea if it's even doable, and how am I suppose do it?

**Comment by Sapiosenses** [comment]
> Got into same problem on my freshly installed arrowos13. I get 'invalid signature" when I want to install from fdroid. Maybe I should grant signature spoofing before trying to install from fdroid? But have no idea if it's even doable, and how am I suppose do it?


Some F-droid clients are not handling the new dual signatures properly, it appears. Aurora Droid seems to be one of them.

If you are using that F-droid client, try the regular F-droid client or Neo Store.

Are you using the microG F-droid repo?

[
](https://microg.org/fdroid.html)

**Comment by robinpaulson** [comment]
Hi, i can't get gmscore to update either, using the microg repo from fdroid. See attached for the error message. ![](https://i.imgur.com/YjJPMX6.png)

**Comment by Sapiosenses** [comment]
> Hi, i can't get gmscore to update either, using the microg repo from fdroid. See attached for the error message. ![]

What F-droid client are you using? 

I have seen issues with non-official F-droid clients not installing that update.

If you're using a non-official F-droid client (like Aurora Droid, etc), try the official F-droid client.

You can also manually install the APK as an update like any other APK file. (System apps can be updated by a regular user, the update inherits the permissions of the previously installed version and Android saves the original one on the system so you can revert if necessary)

**Comment by robinpaulson** [comment]
Thanks, I manually installed it. It had a different key though, do I had to uninstall existing then install the latest. I installed gsf, droid guard and fame store too. Now the self-check complains about signature spoofing not working.

**Comment by robinpaulson** [comment]
![](https://i.imgur.com/7xSsKdP.png)

**Comment by robinpaulson** [comment]
I suspect it is not installed as a system app?

**Comment by ale5000-git** [comment]
The signature isn't changed so maybe you have got the wrong apk.

You can see the link of official apk files here: https://github.com/micro5k/gmscore-info

**Comment by robinpaulson** [comment]
@ale5000-git i'm not sure what this has to do with my situation. I got the apk from microg.org. The issue is signature spoofing isn't working.

**Comment by ale5000-git** [comment]
If your ROM come with a custom version of microG and you install the official microG it is possibile that it will never work.
Some ROMs restrict the signature spoofing to their custom version of microG.
Still you didn't give any info about your device and your ROM so how can people help you?

**Comment by robinpaulson** [comment]
> so how can people help you?

Weirdly passive aggressive. Sapiosenses was able to help, it was appreciated. You haven't helped.

**Comment by ale5000-git** [comment]
All people here help for free, but many people just write unclear tickets expecting to be helped for free and not even bother to write the proper details to be helped.

Plus you haven't even written the topsecret name of your ROM :)

**Comment by Komprogue** [comment]
> Should also be fixed now (see upstream issue: https://gitlab.com/fdroid/fdroidclient/-/issues/2426)

 _Oh, sh*t, here we go again._

Update f-droid to the latest 1.16 build brings back signature incompability bug again. But this time it seems that f-droid's fault, not microg repository redirecting issue (?)

**Comment by defkev** [comment]
Same problem after updating F-Droid to 1.16.1

> incompatible signature

I suppose this has something to do with F-Droid now keeping repository metadata cached even after disabling/enabling a repo and is unrelated to the, since fixed, redirect "bug" from a couple of weeks ago which completely failed to fetch the microG repo.

Haven't dug any further yet tho.
