### ISSUE TITLE
de.dhl.paket (Post & DHL) crashes on startup, "DynamicLinks.API is not available on this device."

### ISSUE THREAD

**Issue by felurx** [microg/GmsCore#1901]
Hey there!
I just updated the app of the German postal services, and now it crashes after less than a second on the splash screen.

Here's the log entry from one crash:
<details><summary>Output from `adb logcat -b crash`</summary>
<p>

03-18 08:50:10.975 17926 17926 E AndroidRuntime: FATAL EXCEPTION: main
03-18 08:50:10.975 17926 17926 E AndroidRuntime: Process: de.dhl.paket, PID: 17926
03-18 08:50:10.975 17926 17926 E AndroidRuntime: c6.a: 17: API: DynamicLinks.API is not available on this device. Connection failed with: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}
03-18 08:50:10.975 17926 17926 E AndroidRuntime:        at d6.a.getException(com.google.android.gms:play-services-base@@18.1.0:18)
03-18 08:50:10.975 17926 17926 E AndroidRuntime:        at d6.k0.a(com.google.android.gms:play-services-base@@18.1.0:5)
03-18 08:50:10.975 17926 17926 E AndroidRuntime:        at com.google.android.gms.common.api.internal.h.d(com.google.android.gms:play-services-base@@18.1.0:48)
03-18 08:50:10.975 17926 17926 E AndroidRuntime:        at com.google.android.gms.common.api.internal.h.c(com.google.android.gms:play-services-base@@18.1.0:10)
03-18 08:50:10.975 17926 17926 E AndroidRuntime:        at com.google.android.gms.common.api.internal.h.o(com.google.android.gms:play-services-base@@18.1.0:190)
03-18 08:50:10.975 17926 17926 E AndroidRuntime:        at com.google.android.gms.common.api.internal.h.m(com.google.android.gms:play-services-base@@18.1.0:92)
03-18 08:50:10.975 17926 17926 E AndroidRuntime:        at com.google.android.gms.common.api.internal.h.n(com.google.android.gms:play-services-base@@18.1.0:59)
03-18 08:50:10.975 17926 17926 E AndroidRuntime:        at com.google.android.gms.common.api.internal.b.handleMessage(com.google.android.gms:play-services-base@@18.1.0:932)
03-18 08:50:10.975 17926 17926 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
03-18 08:50:10.975 17926 17926 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:226)
03-18 08:50:10.975 17926 17926 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:313)
03-18 08:50:10.975 17926 17926 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
03-18 08:50:10.975 17926 17926 E AndroidRuntime:        Suppressed: oj.i0: [w1{Cancelling}@2712861, Dispatchers.Main.immediate]

</p>
</details> 

I tried rebooting, deleting the app data, and messing with the "Open supported links"/"Supported web addresses" of the app, to no avail. I didn't really find anything when searching for the error message online or in the issues here.
It looks like this has something to do with DynamicLinks, which were requested in #999 and implemented in PRs linked in that issue.

If there is some other info I can provide, things I can try or anything else I can do to help with debugging this, I'd be happy to.

**Comment by RobertoWa** [comment]
for me,

android 10 stock,
microg latest version,

dhl app works fine.

**Comment by felurx** [comment]
@RobertoWa Interesting! Are you on the latest version of Post & DHL? The version I have is 9.0.4.12-(e0421304ba), I updated this morning from Aurora.

**Comment by mar-v-in** [comment]
I just tried with the same version and don't have any issues.
Which version of microG are you using? What's shown on the microG Self-Check?

**Comment by RobertoWa** [comment]
my app is "Post & DHL App Version 9.2.0.47 (b62e857550)"

**Comment by felurx** [comment]
I just took a look, and I did get an update to 9.2.0.47 via Aurora, right after updating to 9.0.4.12 this morning. Still crashes with the same error tho.

@mar-v-in The microG self-check has all boxes ticked, and I'm on 0.2.27.223616, which I think is the latest version?

**Comment by mar-v-in** [comment]
I just updated to 9.2.0.47 to confirm, and it's still working for me. Are you logged in? Have you tried deleting the app's data?

**Comment by felurx** [comment]
@mar-v-in Deleting the apps data, even uninstalling and reinstalling, didn't work :/
Where should I log in/out?

**Comment by adrian5** [comment]
@felurx You can log in/out under the app's right-most menu "Mehr".

**Comment by felurx** [comment]
@adrian5 Ah. I think I was logged in, but after deleting the app's data I'm not. And since the app crashes at start-up, there's not much logging in or out I can do :/

**Comment by 4z3** [comment]
I've got the same problem. Post & DHL 8.4.0.0 is the last working version, but unfortunately it cannot be used anymore as the app tells that it is "deactivated" ("Deaktiviert"). All 9.0 and 9.2 versions up to 9.2.0.47 crash on startup.

**Comment by mar-v-in** [comment]
Can those that have problems and those that don't state their Android version, please?

**Comment by ichrispa** [comment]
I'd like to join the bughunt - de.dhl.paket version 9.2.0.47 (b62e857550) supplied over Aurora. Runs on Android 10 (Lineage 17.1 osprey). MicroG Services Core,  Services Framework Proxy and UnifiedNlp (GAPPS) are installed via FDroid. 

de.dhl.paket crashes on startup. Data/Cache was cleared, app reinstalled, phone rebooted. `adb` provides the identical error as that of the OP.

@mar-v-in:  How do I check where microG was installed? What am I looking for?

**Comment by felurx** [comment]
I'm on Android 13 on a Samsung S21+, with the official Samsung ROM modified.

I'm not sure how I installed microG, but if someone tells me how to check I will.

**Comment by 4z3** [comment]
Android 11 (crDroid 7.13). I didn't specifically install microG to /system, but added the microG repo to f-droid and installed it from there.

**Comment by ale5000-git** [comment]
For all: if you don't know then it is installed in the data partition.
To install as system app (that is the only way to have it completely working on newer ROMs) you have to use root or recovery.

**Comment by RobertoWa** [comment]
there is a new release of the app. changelog says there is a fix for start crashes.

**Comment by ichrispa** [comment]
I can confirm too that version 9.2.1.50, installed over Aurora, mitigates the problem in the app. Can't say if they worked around the problem (i.e. microG still has something to fix) or if it was a problem on the Apps side in the first place :shrug: 
Thank @RobertoWa for pointing that out :)

**Comment by felurx** [comment]
I finally got the update via Aurora too, now. I thin that the problem is fixed now, so I'll close this issue. Thank you everybody who commented!

**Comment by philippludwig** [comment]
Seems like the problem is back with version 9.3.3.61. Downgrading to version 9.3.2.56 (version code 921500056) seems to work for now. Thanks at everyone here for the discussion, this helped me to fix it for me.

**Comment by real-or-random** [comment]
Perhaps this helps somebody: I just had crashes related to Firebase, but clearing the app data helped.
```
FATAL EXCEPTION: main
Process: de.dhl.paket, PID: 7947
java.util.concurrent.ExecutionException: java.io.IOException: SERVICE_NOT_AVAILABLE
	at com.google.android.gms.tasks.Tasks.zza(com.google.android.gms:play-services-tasks@@18.0.2:32)
	at com.google.android.gms.tasks.Tasks.await(com.google.android.gms:play-services-tasks@@18.0.2:8)
	at com.google.firebase.messaging.FirebaseMessaging.lambda$deleteToken$6(FirebaseMessaging.java:7)
	at com.google.firebase.messaging.FirebaseMessaging.j(FirebaseMessaging.java:1)
	at com.google.firebase.messaging.p.run(R8$$SyntheticClass:15)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at com.google.android.gms.common.util.concurrent.zza.run(com.google.android.gms:play-services-basement@@18.1.0:7)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: ri.j0: [z1{Cancelling}@5886e06, Dispatchers.Main.immediate]
Caused by: java.io.IOException: SERVICE_NOT_AVAILABLE
	at com.google.firebase.messaging.GmsRpc.handleResponse(GmsRpc.java:41)
	at com.google.firebase.messaging.GmsRpc.lambda$extractResponseWhenComplete$0(GmsRpc.java:9)
	at com.google.firebase.messaging.GmsRpc.a(GmsRpc.java:1)
	at com.google.firebase.messaging.u.then(R8$$SyntheticClass:3)
	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:27)
	at x1.e.execute(R8$$SyntheticClass:1)
	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.2:8)
	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:36)
	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.2:15)
	at com.google.android.gms.tasks.zzc.run(com.google.android.gms:play-services-tasks@@18.0.2:37)
	at com.google.android.gms.cloudmessaging.zzz.execute(com.google.android.gms:play-services-cloud-messaging@@17.0.0:1)
	at com.google.android.gms.tasks.zzd.zzd(com.google.android.gms:play-services-tasks@@18.0.2:8)
	at com.google.android.gms.tasks.zzr.zzb(com.google.android.gms:play-services-tasks@@18.0.2:36)
	at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.2:15)
	at com.google.android.gms.tasks.TaskCompletionSource.setResult(com.google.android.gms:play-services-tasks@@18.0.2:3)
	at com.google.android.gms.cloudmessaging.zzp.zzd(com.google.android.gms:play-services-cloud-messaging@@17.0.0:47)
	at com.google.android.gms.cloudmessaging.zzr.zza(com.google.android.gms:play-services-cloud-messaging@@17.0.0:11)
	at com.google.android.gms.cloudmessaging.zzf.handleMessage(com.google.android.gms:play-services-cloud-messaging@@17.0.0:110)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7924)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

**Comment by PlexSheep** [comment]
The app doesn't seem to work anymore. I've tried to open a Packstation, but the app couldn't find the Packstation, even though it shows up on the regular Bluetooth search.

**Comment by philippludwig** [comment]
> The app doesn't seem to work anymore. I've tried to open a Packstation, but the app couldn't find the Packstation, even though it shows up on the regular Bluetooth search.

Most likely you ran into the regular connection bug that existed for years on the DHL app, even using google play services. It worked for me usually when I "force quit" the DHL app and restarted it.
