### ISSUE TITLE
[com.dexcom.g7] "Check your internet connection and try again"

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [microg/GmsCore#2178]
**Affected app**
Name: [e.g. Dexcom G7]
Package id: [e.g. com.dexcom.g7]

**Describe the bug**
When attempting to log into the Dexcom app, it just says to check your internet connection and try again.

**To Reproduce**
1. Install the Dexcom G7 app
2. Attempt to login to your Dexcom app
3. Error shows

**Expected behavior**
The app allows you to log into your Dexcom app

**Screenshots**
![image](https://github.com/microg/GmsCore/assets/78825510/508b70a9-1d2b-45bd-a857-da7514e8e9fa)

**System**
Android Version: 13
Custom ROM: crDroid 9.13
Phone: Samsung Galaxy S6 (codename zerofltebmc, model number SM-G920W8)

**microG**
microG Core version: v0.3.0.233515
microG Self-Check results: All ticked

**Comment by Lost-Entrepreneur439** [comment]
Fixed in v0.3.1.240913

**Comment by DvopHeh** [comment]
hey there, sorry to reopen the issue, I just installed Dexcom G7 (latest) through Aurora with microg and still get the same error, any possible idea why would that be? I might be dumb, I'm sorry

**Comment by Lost-Entrepreneur439** [comment]
> hey there, sorry to reopen the issue, I just installed Dexcom G7 (latest) through Aurora with microg and still get the same error, any possible idea why would that be? I might be dumb, I'm sorry
> 
> microg version: 0.3.6.244735-27
> dexcom version: 2.8.0

use BYOD

**Comment by DvopHeh** [comment]
> > hey there, sorry to reopen the issue, I just installed Dexcom G7 (latest) through Aurora with microg and still get the same error, any possible idea why would that be? I might be dumb, I'm sorry
> > microg version: 0.3.6.244735-27
> > dexcom version: 2.8.0
> 
> use BYOD

oh yeah, that worked, thank you!!
