### ISSUE TITLE
Timeline not work on google maps

### ISSUE THREAD

**Issue by Ahmed0banna** [microg/GmsCore#2785]
Timeline dont work on latest microG

1-open google maps 
2-click your profile 
3-choose timeline

My device HUAWEI P60 PRO with EMUI 14.2

![Image](https://github.com/user-attachments/assets/6cf11623-5fa0-4e92-b060-9e5362a145b0)

**Comment by ale5000-git** [comment]
This is possibly fixed by this: #2767
But it can't be tested now unless you know how to compile it yourself so you need to wait for it to be merged and a new version of microG released.

**Comment by Sdaniels3152** [comment]
> This is possibly fixed by this: [#2767](https://github.com/microg/GmsCore/pull/2767) But it can't be tested now unless you know how to compile it yourself so you need to wait for it to be merged and a new version of microG released.

Yes, this fixed the access to the timeline. Thanks.
But I still can't record any place or access timelime backups. It also says Timeline is not activated, when it is. 
My device is HUAWEI P60 PRO with EMUI 14.2

This screenshot is after I click on the cloud icon. 
![Image](https://github.com/user-attachments/assets/a48669be-4c85-4bcc-8886-e52a560a4640)

This one when I try to check the settings
![Image](https://github.com/user-attachments/assets/66c0fae7-a503-4d53-85f2-85dd07126e22)

**Comment by simzen85** [comment]
similar issue
