### ISSUE TITLE
Weblate strangeness

### ISSUE THREAD

**Issue by ale5000-git** [microg/GmsCore#2846]
@mar-v-in
On Weblate in almost all components it say ![Image](https://github.com/user-attachments/assets/3571ad45-c5bd-4e1b-87cc-fb13d98fe23b) (This components is linked to the repository microG/...) excluding this one: `play-services-core: strings`.

Is something not linked well?

**Comment by mar-v-in** [comment]
`play-services-core: strings` is using the upstream git repository as source, all other components use the repository of the `play-services-core: strings` component (hence they are linked) instead. If each component was directly using the upstream git independently, squashing changes across components would be much more trouble.

**Comment by ale5000-git** [comment]
@mar-v-in
I admit I didn't understand your reply but if you say it is fine it is.

The other problem is the red icon, after clicking on it it say:
`The VCS repository has many changes compared to the upstream. Merge changes manually or set up push to automate the operation.`

Is this also fine?

**Comment by mar-v-in** [comment]
Fixed now as well (was only a cache that didn't refresh after fixing the issue earlier)

**Comment by ale5000-git** [comment]
Now ti seems that https://hosted.weblate.org/ has problem loading, I'm unlucky today.

**Comment by ale5000-git** [comment]
> Fixed now as well (was only a cache that didn't refresh after fixing the issue earlier)

The red icon is disappeared from `play-services-ads-identifier: core: strings` but it is still present in others,

**Comment by ale5000-git** [comment]
Now it seems everything is fixed, thanks.
